#!/usr/bin/env bash
#
# Ported from mattpocock/skills (MIT). Copyright (c) 2026 Matt Pocock.
# Upstream: https://github.com/mattpocock/skills
# Commit:   321658273cb1d20b76026717d027d505790106d4
# Upstream path: skills/engineering/wizard/template.sh
# This attribution header is the only sanctioned edit; the rest is verbatim.
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Provisions one trial deployment; docs/trial-deployment.md says why each stage is
# shaped the way it is. Usage, from anywhere:
#   bash scripts/trial-wizard.sh <slug>            every stage not done yet
#   bash scripts/trial-wizard.sh <slug> --from N   stage N and every one after it, again
#   bash scripts/trial-wizard.sh <slug> receipts   only the closing receipts stage
# State lives in .env.trial-<slug>-wizard at the repo root, beside the secrets files.

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
[[ -f scripts/provision_trial.py ]] || { echo "Run this from the cyris checkout."; exit 1; }

SLUG="${1:-}"
MODE="${2:-all}"
FROM=""
if [[ "$MODE" == --from ]]; then FROM="${3:-}"; fi
if [[ ! "$SLUG" =~ ^[a-z][a-z0-9]{1,19}$ || "$SLUG" == wizard ]] \
  || [[ "$MODE" != all && "$MODE" != receipts && "$MODE" != --from ]] \
  || [[ "$MODE" == --from && ! "$FROM" =~ ^([1-9]|1[0-7])$ ]]; then
  echo "Usage: bash scripts/trial-wizard.sh <slug> [receipts | --from N]"
  echo "slug: 2-20 lowercase letters or digits, starting with a letter, not 'wizard'."
  echo "N: a stage from 1 to 17."
  exit 1
fi
LOGIN_WAIT_SECONDS="${TRIAL_WIZARD_LOGIN_WAIT:-2400}"
LOGIN_WAIT_INTERVAL="${TRIAL_WIZARD_LOGIN_INTERVAL:-30}"

STATE=".env.trial-$SLUG-wizard"
APP_ENV=".env.trial-$SLUG"
PROMOTE_ENV=".env.trial-$SLUG-promote"
RSS_ENV=".env.trial-$SLUG-rss"
SOURCES_FILE=".env.trial-$SLUG-sources.yaml"
APP_CFG="wrangler.trial-$SLUG.toml"
PROMOTE_CFG="workers/promote/wrangler.trial-$SLUG.toml"
RSS_CFG="workers/rss/wrangler.trial-$SLUG.toml"
LOG_DIR=$(mktemp -d)
ENV_FILE="$STATE"

# A token exported by the login shell beats --env-file /dev/null and wrangler's
# OAuth login alike, so it must not reach any wrangler call.
if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  echo "${YELLOW}⚠ CLOUDFLARE_API_TOKEN was exported by your shell; unsetting it for this run.${RESET}"
fi
unset CLOUDFLARE_API_TOKEN GEMINI_API_KEY

# shellcheck disable=SC1090
[[ -f "$STATE" ]] && source "$STATE"
STAGES_DONE="${STAGES_DONE:-}"

die() { printf '\n  %s✗ %s%s\n  Fix it, then re-run: bash scripts/trial-wizard.sh %s\n\n' "$RED" "$1" "$RESET" "$SLUG"; exit 1; }
next() { printf '\n'; pause "Press Enter for the next stage"; }

# show_run LOGNAME CMD... prints the command, runs it with output teed to a log.
show_run() {
  local log="$LOG_DIR/$1.log"; shift
  printf '  %s$%s' "$DIM" "$RESET"; printf ' %q' "$@"; printf '\n'
  "$@" 2>&1 | tee "$log"
}
# gated LOGNAME "question" CMD... asks first; returns 2 when declined.
gated() {
  local name="$1" q="$2"; shift 2
  printf '  %s$%s' "$DIM" "$RESET"; printf ' %q' "$@"; printf '\n'
  if confirm "$q"; then
    "$@" 2>&1 | tee "$LOG_DIR/$name.log"
  else
    note "skipped"; return 2
  fi
}

# in_file FILE CMD... runs a library helper (ask/write_env) against another env file.
in_file() { local saved="$ENV_FILE"; ENV_FILE="$1"; shift; "$@"; ENV_FILE="$saved"; }
fileval() { [[ -f "$1" ]] || return 0; grep -E "^$2=" "$1" | tail -n1 | cut -d= -f2- || true; }

# ask_match KEY "prompt" REGEX loops until the answer matches.
ask_match() {
  while true; do
    ask "$1" "$2"
    [[ "${!1}" =~ $3 ]] && return 0
    warn "That does not look right (expected $3). Try again."
  done
}

wrangler_toml_untouched() {
  [[ -z "$(git status --porcelain wrangler.toml)" ]] || die "wrangler.toml changed. Restore it (git checkout wrangler.toml) before going on."
}

derive_names() {
  local out
  out=$(uv run python scripts/provision_trial.py names --slug "$SLUG" --pages-suffix "$TRIAL_SUFFIX") || die "provision_trial.py names failed."
  eval "$out"
}

login_redirect() {
  local h
  h=$(curl -s -o /dev/null -D - --max-time 30 "https://$SLUG.$DOMAIN/" || true)
  grep -qiE '^HTTP/[0-9.]+ 302' <<<"$h" && grep -qiE '^location: /login\?next=%2F' <<<"$h"
}

# The first trial's new custom domain answered 28 minutes after its deploy.
wait_login_redirect() {
  local start=$SECONDS waited
  until login_redirect; do
    waited=$((SECONDS - start))
    ((waited < LOGIN_WAIT_SECONDS)) \
      || die "No 302 → /login after ${waited}s. See docs/install-cloudflare.md step 6 on a new custom domain."
    printf '  waiting for https://%s.%s/ to answer 302 → /login: %dm%02ds\n' \
      "$SLUG" "$DOMAIN" $((waited / 60)) $((waited % 60))
    sleep "$LOGIN_WAIT_INTERVAL"
  done
  printf '  %s✓%s unauthenticated request → 302 /login?next=%%2F\n' "$GREEN" "$RESET"
}

deploy_app() {
  local rc=0
  gated "$1" "Deploy the trial app Worker with $APP_CFG?" \
    bunx wrangler deploy --config "$APP_CFG" --env-file /dev/null --secrets-file "$APP_ENV" || rc=$?
  [[ $rc -eq 0 || $rc -eq 2 ]] || die "App deploy failed."
}

receipts() {
  stage "Receipts (acceptance criteria)"
  say "Read-only checks. The first digest's run takes minutes: wait for it to end first."
  note "Scheduled runs come at the publish hours; re-run with 'receipts' later to see one."
  printf '\n%s  digest_runs%s\n' "$BOLD" "$RESET"
  show_run d1-runs bunx wrangler d1 execute "$TRIAL_D1_NAME" --remote --config "$RSS_CFG" --env-file /dev/null \
    --command "SELECT id, finished_at, status, period, dry_run, build_sha FROM digest_runs ORDER BY id DESC LIMIT 5" || warn "query failed"
  printf '\n%s  usage_log, last 7 days%s\n' "$BOLD" "$RESET"
  show_run d1-usage bunx wrangler d1 execute "$TRIAL_D1_NAME" --remote --config "$RSS_CFG" --env-file /dev/null \
    --command "SELECT date(logged_at) AS day, count(*) AS runs, sum(api_calls) AS calls, round(sum(cost_usd), 4) AS usd FROM usage_log WHERE logged_at >= date('now', '-7 day') GROUP BY day ORDER BY day" || warn "query failed"
  printf '\n%s  login redirect%s\n' "$BOLD" "$RESET"
  if login_redirect; then printf '  %s✓%s 302 → /login\n' "$GREEN" "$RESET"; else warn "no 302 → /login on https://$SLUG.$DOMAIN/"; fi
  printf '\n%s  production archive still public%s\n' "$BOLD" "$RESET"
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 https://cyris-digest.pages.dev/ || true)
  if [[ "$code" == 200 ]]; then printf '  %s✓%s https://cyris-digest.pages.dev/ → 200\n' "$GREEN" "$RESET"; else warn "https://cyris-digest.pages.dev/ → $code"; fi
  printf '\n%s  cyris doctor --deployment%s\n' "$BOLD" "$RESET"
  note "Expected image sha: ${IMAGE_TAG:-unknown} (production's). 'publishing' fails until the first digest exists; that is not a blocker."
  local dir
  dir=$(mktemp -d)
  {
    echo "CYRIS_STORE_BACKEND=d1"
    echo "CYRIS_HTML_OUTPUT_ENABLED=true"
    echo "CYRIS_PROMOTE_PUBLISH_ENABLED=true"
    grep -E '^(CYRIS_STORE_DATABASE_ID|CLOUDFLARE_ACCOUNT_ID|CLOUDFLARE_API_TOKEN|CYRIS_PROMOTE_PAGES_PROJECT|GEMINI_API_KEY|CYRIS_UI_TOKEN|CYRIS_RSS_WORKER_URL|CYRIS_WORKER_TOKEN|CYRIS_PROMOTE_WORKER_URL|CYRIS_PROMOTE_TOKEN)=' "$APP_ENV"
  } > "$dir/.env"
  (cd "$dir" && env -i HOME="$HOME" PATH="$PATH" uv run --project "$REPO" cyris doctor --deployment "https://$SLUG.$DOMAIN") || warn "doctor exited non-zero; read the lines above"
  rm -r "$dir"
  note "Still by hand: a tester's vote, then cyris promote-sync, then triaged_at set in this D1."
  next
}

# A resumed run skips the stages that set these, so they are rebuilt from the state.
if [[ -n "${ACCOUNT_ID:-}" ]]; then export CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID"; fi
if [[ -n "${TRIAL_SUFFIX:-}" ]]; then derive_names; fi

if [[ "$MODE" == receipts ]]; then
  [[ -n "${TRIAL_SUFFIX:-}" && -n "${TRIAL_D1_ID:-}" ]] || die "No state in $STATE; run the full wizard first."
  TOTAL_STAGES=1
  receipts
  finish
  exit 0
fi

# ── 1 ─────────────────────────────────────────────────────────────────────
stage_1() {
  stage "Before you start: Access policy and the wrangler login"
  say "A wildcard Access policy on the trial's domain would give the tester a second login."
  open_url "https://one.dash.cloudflare.com/"
  step "Zero Trust → Access → Applications: check no policy covers <slug>.<domain> (e.g. *.<domain>)."
  pause "Checked, no policy covers it? Press Enter"
  say "Log wrangler in as the account the trial belongs to."
  if confirm "Log wrangler in now? (No if it already is, as that account)"; then
    bunx wrangler login --env-file /dev/null || die "Login did not finish."
  fi
  next
}

# ── 2 ─────────────────────────────────────────────────────────────────────
stage_2() {
  stage "Inputs"
  ask_match DOMAIN "Domain on the trial account's Cloudflare (e.g. example.com):" '^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$'
  ask_match ACCOUNT_ID "Trial account id (32 hex):" '^[0-9a-f]{32}$'
  ask TESTER_EMAIL "Tester's email for digests (empty = no mail):"
  ask_match OUTPUT_LANGUAGE "Tester's output language, BCP 47 (zh-Hant, en, ja, ...):" '^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*$'
  ask_match MAX_ARTICLES "Article cap per digest, agreed with the tester (below 400):" '^([1-9][0-9]?|[1-3][0-9][0-9])$'
  write_env DOMAIN "$DOMAIN"
  write_env ACCOUNT_ID "$ACCOUNT_ID"
  write_env TESTER_EMAIL "$TESTER_EMAIL"
  write_env OUTPUT_LANGUAGE "$OUTPUT_LANGUAGE"
  write_env MAX_ARTICLES "$MAX_ARTICLES"
  export CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID"
  local WHOAMI
  WHOAMI=$(bunx wrangler whoami --env-file /dev/null 2>&1 || true)
  grep -q "$ACCOUNT_ID" <<<"$WHOAMI" || die "The logged-in wrangler cannot see account $ACCOUNT_ID. Log in as that account (stage 1)."
  printf '  %s✓%s wrangler can reach account %s\n' "$GREEN" "$RESET" "$ACCOUNT_ID"
  if [[ -z "${IMAGE_DIGEST:-}" ]]; then
    git fetch --tags
    IMAGE_TAG=$(git tag -l 'image/*' --sort=-creatordate | head -1)
    IMAGE_DIGEST=$(git tag -l --format='%(contents)' "$IMAGE_TAG" | grep -o 'sha256:[0-9a-f]\{64\}' || true)
    [[ "$IMAGE_DIGEST" =~ ^sha256:[0-9a-f]{64}$ ]] || die "No sha256 digest in tag $IMAGE_TAG."
    say "Newest image: $IMAGE_TAG ($IMAGE_DIGEST)"
    note "Production's last deploy: $(gh run list --workflow deploy.yml --limit 1 --json headSha,conclusion -q '.[0] | "\(.headSha) \(.conclusion)"' 2>/dev/null || echo 'gh unavailable')"
    note "The tag's short sha must prefix that commit."
    confirm "Is $IMAGE_TAG the image production runs?" || die "Pick the image production runs before deploying a trial."
    write_env IMAGE_TAG "$IMAGE_TAG"
    write_env IMAGE_DIGEST "$IMAGE_DIGEST"
  else
    note "Keeping $IMAGE_TAG ($IMAGE_DIGEST) from the first run."
  fi
  if [[ -z "${TRIAL_SUFFIX:-}" ]]; then
    TRIAL_SUFFIX=$(openssl rand -hex 8)
    write_env TRIAL_SUFFIX "$TRIAL_SUFFIX"
  else
    note "Keeping TRIAL_SUFFIX $TRIAL_SUFFIX from the first run."
  fi
  next
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage_3() {
  stage "Resource names"
  derive_names
  say "App Worker:     $TRIAL_APP_WORKER"
  say "Container:      $TRIAL_CONTAINER"
  say "Vote Worker/KV: $TRIAL_PROMOTE_WORKER"
  say "D1:             $TRIAL_D1_NAME"
  say "Pages project:  $TRIAL_PAGES_PROJECT"
  say "rss Worker:     $TRIAL_RSS_WORKER"
  note "provision_trial.py guarantees none equals a production name."
  next
}

# ── 4 ─────────────────────────────────────────────────────────────────────
stage_4() {
  stage "Create the D1 database"
  if [[ -n "${TRIAL_D1_ID:-}" ]]; then
    note "Already created: $TRIAL_D1_ID"
  else
    note "If wrangler offers to add a binding to a config file, answer No."
    note "If it reports that the name exists, stop: something already uses this slug."
    printf '  %s$%s bunx wrangler d1 create %s --env-file /dev/null\n' "$DIM" "$RESET" "$TRIAL_D1_NAME"
    confirm "Create D1 database $TRIAL_D1_NAME?" || die "Stopped before creating D1."
    bunx wrangler d1 create "$TRIAL_D1_NAME" --env-file /dev/null || die "d1 create failed."
    ask_match TRIAL_D1_ID "Paste the database UUID it printed:" '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    write_env TRIAL_D1_ID "$TRIAL_D1_ID"
  fi
  wrangler_toml_untouched
  next
}

# ── 5 ─────────────────────────────────────────────────────────────────────
stage_5() {
  stage "Create the KV namespace"
  if [[ -n "${TRIAL_KV_ID:-}" ]]; then
    note "Already created: $TRIAL_KV_ID"
  else
    note "If wrangler offers to add a binding to a config file, answer No. If the name exists, stop."
    printf '  %s$%s bunx wrangler kv namespace create %s --env-file /dev/null\n' "$DIM" "$RESET" "$TRIAL_KV_TITLE"
    confirm "Create KV namespace $TRIAL_KV_TITLE?" || die "Stopped before creating KV."
    bunx wrangler kv namespace create "$TRIAL_KV_TITLE" --env-file /dev/null || die "kv namespace create failed."
    ask_match TRIAL_KV_ID "Paste the namespace id it printed (32 hex):" '^[0-9a-f]{32}$'
    write_env TRIAL_KV_ID "$TRIAL_KV_ID"
  fi
  wrangler_toml_untouched
  next
}

# ── 6 ─────────────────────────────────────────────────────────────────────
stage_6() {
  stage "Create the Pages project"
  if [[ "${PAGES_CREATED:-}" == yes ]]; then
    note "Already created: $TRIAL_PAGES_PROJECT.pages.dev"
  else
    printf '  %s$%s bunx wrangler pages project create %s --production-branch main --env-file /dev/null\n' "$DIM" "$RESET" "$TRIAL_PAGES_PROJECT"
    confirm "Create Pages project $TRIAL_PAGES_PROJECT?" || die "Stopped before creating the Pages project."
    bunx wrangler pages project create "$TRIAL_PAGES_PROJECT" --production-branch main --env-file /dev/null || die "pages project create failed."
    confirm "Did the output name $TRIAL_PAGES_PROJECT.pages.dev exactly?" || die "Pages gave another subdomain; do not go on."
    write_env PAGES_CREATED yes
  fi
  wrangler_toml_untouched
  printf '  %s✓%s wrangler.toml untouched\n' "$GREEN" "$RESET"
  next
}

# ── 7 ─────────────────────────────────────────────────────────────────────
stage_7() {
  stage "The trial's API token and Gemini key"
  say "A token of the trial's own, so a leak reaches only the trial and is revoked alone."
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Create Token → Custom token, scoped to account $ACCOUNT_ID, with account permissions:"
  step "  D1 → Edit · Cloudflare Pages → Edit · Workers Scripts → Read"
  [[ -n "$TESTER_EMAIL" ]] && step "  Email Sending → Edit (the tester gets mail)"
  in_file "$APP_ENV" ask_secret CLOUDFLARE_API_TOKEN "Paste the token (hidden):"
  [[ -n "$CLOUDFLARE_API_TOKEN" ]] || die "Empty token."
  in_file "$APP_ENV" write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
  unset CLOUDFLARE_API_TOKEN
  say "GEMINI_API_KEY is the only LLM key a trial gets; its own budget is the hard stop."
  open_url "https://aistudio.google.com/apikey"
  step "Create (or pick) a key whose project has a budget you accept for this trial."
  in_file "$APP_ENV" ask_secret GEMINI_API_KEY "Paste the Gemini key (hidden):"
  [[ -n "$GEMINI_API_KEY" ]] || die "Empty Gemini key."
  in_file "$APP_ENV" write_env GEMINI_API_KEY "$GEMINI_API_KEY"
  unset GEMINI_API_KEY
  next
}

# ── 8 ─────────────────────────────────────────────────────────────────────
stage_8() {
  stage "Render the trial's configs"
  show_run render uv run python scripts/provision_trial.py render --slug "$SLUG" --domain "$DOMAIN" \
    --account-id "$ACCOUNT_ID" --image-digest "$IMAGE_DIGEST" --kv-id "$TRIAL_KV_ID" --d1-id "$TRIAL_D1_ID" \
    || die "render failed."
  for f in "$APP_CFG" "$PROMOTE_CFG" "$RSS_CFG"; do
    [[ -f "$f" ]] || die "$f was not written."
    git check-ignore -q "$f" || die "$f is not gitignored."
  done
  printf '  %s✓%s three configs written, all gitignored\n' "$GREEN" "$RESET"
  next
}

# ── 9 ─────────────────────────────────────────────────────────────────────
stage_9() {
  stage "Dry-run all three configs"
  (cd workers/rss && bun install --frozen-lockfile) || die "bun install in workers/rss failed."
  show_run dry-app bunx wrangler deploy --dry-run --config "$APP_CFG" --env-file /dev/null || die "App dry run failed."
  show_run dry-promote bunx wrangler deploy --dry-run --config "$PROMOTE_CFG" --env-file /dev/null || die "Vote Worker dry run failed."
  show_run dry-rss bunx wrangler deploy --dry-run --config "$RSS_CFG" --env-file /dev/null || die "rss Worker dry run failed."
  printf '\n  %s✓%s all three dry runs passed\n' "$GREEN" "$RESET"
  next
}

# ── 10 ────────────────────────────────────────────────────────────────────
stage_10() {
  stage "Deploy the vote Worker"
  TRIAL_PROMOTE_TOKEN=$(fileval "$PROMOTE_ENV" PROMOTE_TOKEN)
  if [[ -z "$TRIAL_PROMOTE_TOKEN" ]]; then
    TRIAL_PROMOTE_TOKEN=$(openssl rand -hex 32)
    printf 'PROMOTE_TOKEN=%s\n' "$TRIAL_PROMOTE_TOKEN" > "$PROMOTE_ENV"
    printf '  %s✓%s new vote token → %s\n' "$GREEN" "$RESET" "$PROMOTE_ENV"
  else
    note "Keeping the vote token in $PROMOTE_ENV."
  fi
  local rc=0
  gated promote "Deploy the vote Worker with $PROMOTE_CFG?" \
    bunx wrangler deploy --config "$PROMOTE_CFG" --env-file /dev/null --secrets-file "$PROMOTE_ENV" || rc=$?
  [[ $rc -eq 0 || $rc -eq 2 ]] || die "Vote Worker deploy failed."
  if [[ $rc -eq 0 ]]; then
    TRIAL_PROMOTE_URL=$(grep -oE 'https://[a-z0-9.-]+\.workers\.dev' "$LOG_DIR/promote.log" | head -1 || true)
    write_env TRIAL_PROMOTE_URL "$TRIAL_PROMOTE_URL"
  fi
  ask_match TRIAL_PROMOTE_URL "Vote Worker URL (Enter keeps the one shown):" '^https://[a-z0-9.-]+\.workers\.dev$'
  write_env TRIAL_PROMOTE_URL "$TRIAL_PROMOTE_URL"
  next
}

# ── 11 ────────────────────────────────────────────────────────────────────
stage_11() {
  stage "Write the app's secrets file"
  [[ -n "$(fileval "$APP_ENV" CYRIS_UI_TOKEN)" ]] || in_file "$APP_ENV" write_env CYRIS_UI_TOKEN "$(openssl rand -hex 32)"
  in_file "$APP_ENV" write_env CYRIS_STORE_DATABASE_ID "$TRIAL_D1_ID"
  in_file "$APP_ENV" write_env CLOUDFLARE_ACCOUNT_ID "$ACCOUNT_ID"
  in_file "$APP_ENV" write_env CYRIS_PROMOTE_PAGES_PROJECT "$TRIAL_PAGES_PROJECT"
  in_file "$APP_ENV" write_env CYRIS_PROMOTE_WORKER_URL "$TRIAL_PROMOTE_URL"
  in_file "$APP_ENV" write_env CYRIS_PROMOTE_TOKEN "$(fileval "$PROMOTE_ENV" PROMOTE_TOKEN)"
  for k in CYRIS_UI_TOKEN CLOUDFLARE_API_TOKEN GEMINI_API_KEY CYRIS_PROMOTE_TOKEN; do
    [[ -n "$(fileval "$APP_ENV" "$k")" ]] || die "$k is empty in $APP_ENV."
  done
  grep -qx "CYRIS_STORE_DATABASE_ID=$TRIAL_D1_ID" "$APP_ENV" || die "CYRIS_STORE_DATABASE_ID mismatch in $APP_ENV."
  grep -qx "CYRIS_PROMOTE_PAGES_PROJECT=$TRIAL_PAGES_PROJECT" "$APP_ENV" || die "CYRIS_PROMOTE_PAGES_PROJECT mismatch in $APP_ENV."
  if [[ -z "${TRIAL_RSS_URL:-}" ]] && grep -Eq '^(CYRIS_WORKER_TOKEN|CYRIS_RSS_WORKER_URL)=' "$APP_ENV"; then
    die "$APP_ENV names the rss Worker before it exists."
  fi
  grep -Eq '^(CYRIS_PRIVATE_ARCHIVE|CYRIS_APP_WORKER_NAME)=' "$APP_ENV" && die "$APP_ENV would shadow CYRIS_PRIVATE_ARCHIVE or CYRIS_APP_WORKER_NAME."
  printf '  %s✓%s all receipts ok\n' "$GREEN" "$RESET"
  next
}

# ── 12 ────────────────────────────────────────────────────────────────────
stage_12() {
  stage "Deploy the app"
  deploy_app app
  note "The first request starts the container; a new custom domain can take minutes."
  wait_login_redirect
  next
}

# ── 13 ────────────────────────────────────────────────────────────────────
stage_13() {
  stage "First boot: settings and the tester's sources"
  if [[ ! -f "$SOURCES_FILE" ]]; then
    cat > "$SOURCES_FILE" <<'YAML'
defaults:
  tier: filter
  language: auto
sources:
  - name: "Stratechery"
    url: "https://stratechery.com/feed/"
    tier: summarize
    tags: [tech, business-strategy]
YAML
  fi
  say "Replace the example with the tester's feeds: RSS only, never type: newsletter."
  say "Tiers are explained in docs/sources.md. Keep to the source limit you agreed."
  say "File: $REPO/$SOURCES_FILE"
  if confirm "Open it in ${EDITOR:-vi} now?"; then ${EDITOR:-vi} "$SOURCES_FILE"; fi
  pause "Saved the tester's feeds? Press Enter"
  grep -qE 'type:[[:space:]]*"?newsletter' "$SOURCES_FILE" && die "$SOURCES_FILE has a newsletter source; a trial has no newsletter Worker."
  SOURCE_COUNT=$(uv run python -c 'import sys, yaml; print(len(yaml.safe_load(open(sys.argv[1]))["sources"]))' "$SOURCES_FILE") \
    || die "$SOURCES_FILE is not valid YAML with a sources list."
  write_env SOURCE_COUNT "$SOURCE_COUNT"
  say "$SOURCE_COUNT source(s)."
  local TRIAL_DIR
  TRIAL_DIR=$(mktemp -d)
  grep -E '^(CLOUDFLARE_ACCOUNT_ID|CLOUDFLARE_API_TOKEN|CYRIS_STORE_DATABASE_ID|CYRIS_PROMOTE_PAGES_PROJECT)=' "$APP_ENV" > "$TRIAL_DIR/.env"
  sed -e '/^\[llm_provider\]/,/^\[digest\]/s/^provider = .*/provider = "gemini"/' \
      -e '/^\[llm_provider\]/,/^\[digest\]/s/^model = .*/model = "gemini-2.5-flash"/' \
      -e "s/^max_articles_per_digest = .*/max_articles_per_digest = $MAX_ARTICLES/" \
      -e "s/^output_language = .*/output_language = \"$OUTPUT_LANGUAGE\"/" \
      cyris.toml.example > "$TRIAL_DIR/settings.toml"
  grep -qx "output_language = \"$OUTPUT_LANGUAGE\"" "$TRIAL_DIR/settings.toml" || die "output_language did not land in settings.toml."
  cp "$SOURCES_FILE" "$TRIAL_DIR/sources.yaml"
  printf '  %s$%s cyris settings push --config %s/settings.toml --sources %s/sources.yaml\n' "$DIM" "$RESET" "$TRIAL_DIR" "$TRIAL_DIR"
  confirm "Push the settings into the trial's D1?" || die "Stopped before settings push."
  env -i HOME="$HOME" PATH="$PATH" uv run cyris settings push --config "$TRIAL_DIR/settings.toml" --sources "$TRIAL_DIR/sources.yaml" \
    | tee "$TRIAL_DIR/settings-push.log" || die "settings push failed."
  head -1 "$TRIAL_DIR/settings-push.log" | grep -qx "D1 database $TRIAL_D1_ID" \
    || die "settings push wrote to a database other than $TRIAL_D1_ID. Stop and check."
  printf '  %s✓%s settings push went to %s\n' "$GREEN" "$RESET" "$TRIAL_D1_ID"
  env -i HOME="$HOME" PATH="$PATH" uv run cyris sources push --config "$TRIAL_DIR/settings.toml" --sources "$TRIAL_DIR/sources.yaml" \
    || die "sources push failed."
  rm -r "$TRIAL_DIR"
  next
}

# ── 14 ────────────────────────────────────────────────────────────────────
stage_14() {
  stage "The rss Worker"
  TRIAL_WORKER_TOKEN=$(fileval "$RSS_ENV" RSS_TOKEN)
  if [[ -z "$TRIAL_WORKER_TOKEN" ]]; then
    TRIAL_WORKER_TOKEN=$(openssl rand -hex 32)
    printf 'RSS_TOKEN=%s\n' "$TRIAL_WORKER_TOKEN" > "$RSS_ENV"
  fi
  grep -qx "RSS_TOKEN=$TRIAL_WORKER_TOKEN" "$RSS_ENV" || die "$RSS_ENV does not hold the token."
  local rc=0 code poll feeds
  gated rss "Deploy the rss Worker with $RSS_CFG?" \
    bunx wrangler deploy --config "$RSS_CFG" --env-file /dev/null --secrets-file "$RSS_ENV" || rc=$?
  [[ $rc -eq 0 || $rc -eq 2 ]] || die "rss Worker deploy failed."
  if [[ $rc -eq 0 ]]; then
    TRIAL_RSS_URL=$(grep -oE 'https://[a-z0-9.-]+\.workers\.dev' "$LOG_DIR/rss.log" | head -1 || true)
    write_env TRIAL_RSS_URL "$TRIAL_RSS_URL"
  fi
  ask_match TRIAL_RSS_URL "rss Worker URL (Enter keeps the one shown):" '^https://[a-z0-9.-]+\.workers\.dev$'
  write_env TRIAL_RSS_URL "$TRIAL_RSS_URL"
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$TRIAL_RSS_URL/stats" || true)
  [[ "$code" == 401 ]] || die "$TRIAL_RSS_URL/stats without the bearer answered $code, not 401."
  printf '  %s✓%s /stats without the bearer → 401\n' "$GREEN" "$RESET"
  poll=$(curl -s -X POST --max-time 120 -H "Authorization: Bearer $TRIAL_WORKER_TOKEN" "$TRIAL_RSS_URL/poll" || true)
  say "/poll: $poll"
  feeds=$(grep -oE '"feeds":[0-9]+' <<<"$poll" | cut -d: -f2 || true)
  [[ "$feeds" == 0 ]] && die "/poll reports feeds 0: the first boot pushed no RSS source. Go back to stage 13."
  [[ "$feeds" == "$SOURCE_COUNT" ]] || die "/poll reports feeds '$feeds', sources push had $SOURCE_COUNT."
  printf '  %s✓%s /poll feeds = %s\n' "$GREEN" "$RESET" "$feeds"
  in_file "$APP_ENV" write_env CYRIS_WORKER_TOKEN "$TRIAL_WORKER_TOKEN"
  in_file "$APP_ENV" write_env CYRIS_RSS_WORKER_URL "$TRIAL_RSS_URL"
  grep -qx "CYRIS_WORKER_TOKEN=$TRIAL_WORKER_TOKEN" "$APP_ENV" || die "CYRIS_WORKER_TOKEN did not land."
  grep -qx "CYRIS_RSS_WORKER_URL=$TRIAL_RSS_URL" "$APP_ENV" || die "CYRIS_RSS_WORKER_URL did not land."
  say "Redeploy so the app reads them."
  deploy_app app-rss
  wait_login_redirect
  next
}

# ── 15 ────────────────────────────────────────────────────────────────────
stage_15() {
  stage "Let the tester receive mail"
  if [[ -z "$TESTER_EMAIL" ]]; then
    note "No tester email; skipping."
  else
    open_url "https://dash.cloudflare.com/$ACCOUNT_ID"
    step "Email Service → Email Routing → Destination Addresses → add $TESTER_EMAIL."
    step "Ask the tester to open the verification mail before they save Notifications on /settings."
    note "Save on /settings stores the pair only if the test message is delivered."
    pause "Destination added? Press Enter"
  fi
  next
}

# ── 16 ────────────────────────────────────────────────────────────────────
stage_16() {
  stage "Hand over"
  say "Login: https://$SLUG.$DOMAIN/login"
  if command -v pbcopy >/dev/null 2>&1; then
    fileval "$APP_ENV" CYRIS_UI_TOKEN | tr -d '\n' | pbcopy
    printf '  %s✓%s CYRIS_UI_TOKEN copied to the clipboard\n' "$GREEN" "$RESET"
  else
    say "CYRIS_UI_TOKEN is in $APP_ENV."
  fi
  step "Put it in a password manager item shared with the tester; never chat or email."
  step "The tester finishes /settings: Discord webhook, mail sender/recipient, anything else."
  pause "Shared? Press Enter"
  if command -v pbcopy >/dev/null 2>&1 && confirm "Clear the clipboard?"; then printf '' | pbcopy; fi
  warn "Keep $APP_ENV, $PROMOTE_ENV and $RSS_ENV: Cloudflare cannot read secrets back."
  next
}

# ── 17 ────────────────────────────────────────────────────────────────────
stage_17() {
  stage "Start the first digest"
  ask_match PERIOD "Period, morning or evening:" '^(morning|evening)$'
  local SESSION reply
  SESSION=$(fileval "$APP_ENV" CYRIS_UI_TOKEN | tr -d '\n' | shasum -a 256 | cut -d' ' -f1)
  if confirm "POST https://$SLUG.$DOMAIN/run?period=$PERIOD now?"; then
    reply=$(curl -s -X POST --max-time 180 -b "cyris_session=$SESSION" "https://$SLUG.$DOMAIN/run?period=$PERIOD" || true)
    say "Reply: $reply"
    if grep -q '"started"' <<<"$reply"; then
      printf '  %s✓%s run started; it takes minutes\n' "$GREEN" "$RESET"
    else
      warn "No 'started' reply. A cold container may still have started the run: tail the log before posting again."
    fi
  fi
  say "Watch it end with a run_summary line (Ctrl-C to stop tailing):"
  note "bunx wrangler tail --config $APP_CFG --env-file /dev/null"
  if confirm "Tail the app's log now?"; then
    bunx wrangler tail --config "$APP_CFG" --env-file /dev/null || true
  fi
  next
}

# ── 18 is receipts(), above. ─────────────────────────────────────────────

is_done() { [[ ",${STAGES_DONE:-}," == *",$1,"* ]]; }

# Progress is not a library value: write_env would list it in finish()'s summary.
save_progress() {
  local tmp; tmp=$(mktemp)
  grep -v '^STAGES_DONE=' "$STATE" > "$tmp" || true
  printf 'STAGES_DONE=%s\n' "$STAGES_DONE" >> "$tmp"
  mv "$tmp" "$STATE"
}

mark_done() {
  STAGES_DONE=$(printf '%s\n' ${STAGES_DONE//,/ } "$1" | sort -n | uniq | paste -sd, -)
  save_progress
}

STAGE_FNS=(stage_1 stage_2 stage_3 stage_4 stage_5 stage_6 stage_7 stage_8 stage_9 \
  stage_10 stage_11 stage_12 stage_13 stage_14 stage_15 stage_16 stage_17 receipts)
TOTAL_STAGES=${#STAGE_FNS[@]}

if [[ -n "$FROM" ]]; then
  STAGES_DONE=$(printf '%s\n' ${STAGES_DONE//,/ } | awk -v from="$FROM" '$1 < from' | paste -sd, -)
  touch "$STATE"
  save_progress
fi

banner "cyris trial deployment: $SLUG"

if [[ -n "${STAGES_DONE:-}" ]]; then
  say "Stages ${STAGES_DONE//,/, } were done earlier and are skipped."
  note "To redo one and everything after it: bash scripts/trial-wizard.sh $SLUG --from N"
  pause "Press Enter to go on"
fi

for ((n = 1; n <= TOTAL_STAGES; n++)); do
  if is_done "$n"; then continue; fi
  _STAGE_INDEX=$((n - 1))
  "${STAGE_FNS[$((n - 1))]}"
  # receipts reads only, so it runs again on every pass.
  if ((n < TOTAL_STAGES)); then mark_done "$n"; fi
done

finish
rm -r "$LOG_DIR"
